# Generated by Django 4.2.2 on 2023-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='current_company',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_working_day',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='notice_period',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='preferred_location',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='profile',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='work_mode',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
    ]
